id: Gym-Grid/Gridworld-Snake-6x6-v0
monitor:
  button_cell_id: 31
  button_flip_act: 1
  forbidden_states:
    - 2
    - 8
#    - 14
    - 20
    - 26
    - 32

experiment:
  training_steps: 1000000
  testing_episodes: 100
  testing_frequency: 10000
  beta: 1.02

critic:
  gamma: 0.99
  joint_max_q: 10
  env_min_r: -10
  ucb_a: 0.0004
  ucb_b: 0.0004
