id: Gym-Grid/Gridworld-Bottleneck
monitor:
  button_cell_id: 31
  button_flip_act: 1
  forbidden_states:
    - 2
    - 8
#    - 14
    - 20
    - 26
    - 32

experiment:
  training_steps: 30000
  testing_episodes: 100
  testing_frequency: 100
  kappa_base: 1.005

critic:
  gamma: 0.99
  joint_max_q: 1
  env_min_r: -10
  beta_e: 0.0005
  beta_m: 0.0005
  beta: 0.0005
  beta_obs: 0.0005
  beta_kl_ucb: 0.0005