id: Gym-Grid/Gridworld-Bypass-3x5-v0
monitor:
  button_cell_id: 13
  button_flip_act: 1
  forbidden_states:
    - 7
    - 8


experiment:
  training_steps: 20000
  testing_episodes: 100
  testing_frequency: 100
  beta: 1.025

critic:
  gamma: 0.99
  joint_max_q: 1
  env_min_r: -10
  ucb_a: 0.0004
  ucb_b: 0.0004
  ucb_c: 0.0004
