id: Gym-Grid/Gridworld-Empty-Distract-6x6-v0
monitor:
  button_cell_id: 0
  button_flip_act: 0
  forbidden_states:


experiment:
  training_steps: 25000
  testing_episodes: 100
  testing_frequency: 100
  beta: 1.025

critic:
  gamma: 0.99
  joint_max_q: 1
  env_min_r: 0
  ucb_a: 0.0004
  ucb_b: 0.0004
  ucb_c: 0.0004