id: Gym-Grid/Gridworld-Empty-Distract-6x6-v0
monitor:
  button_cell_id: 31
  button_flip_act: 1
  forbidden_states:
    - 2
    - 8
#    - 14
    - 20
    - 26
    - 32

experiment:
  training_steps: 20000
  testing_episodes: 100
  testing_frequency: 100
  beta1: 0.05
  beta2: 0.5

critic:
  gamma: 0.99
  joint_max_q: 10
  obsrv_max_q: 100
  env_min_r: -1
  ucb_re: 0.004
  ucb_rm: 0.004
  ucb_p: 0.004
