id: Gym-Grid/Gridworld-Empty-Distract-6x6-v0
monitor:
  button_cell_id: 31
  button_flip_act: 1
  forbidden_states:
    - 2
    - 8
#    - 14
    - 20
    - 26
    - 32

experiment:
  training_steps: 20000
  testing_episodes: 100
  testing_frequency: 100
  beta: 0.01

critic:
  gamma: 0.99
  q_max: 10
  r_min: -1
  ucb_re: 0.004
  ucb_rm: 0.004
  ucb_p: 0.004