id: Gym-Grid/Gridworld-Penalty-3x3-v0
monitor:
  button_cell_id: 8
  button_flip_act: 1
  forbidden_states:
    - 1
    - 4

experiment:
  training_steps: 20000
  testing_episodes: 100
  testing_frequency: 1000
  beta: 1.025

critic:
  gamma: 0.99
  joint_max_q: 10
  env_min_r: -10
  ucb_a: 0.004
  ucb_b: 0.004
  ucb_c: 0.004
