id: Gym-Grid/Gridworld-Penalty-3x3-v0
monitor:
  button_cell_id: 8
  button_flip_act: 1
  forbidden_states:
    - 1
    - 4

experiment:
  training_steps: 20000
  testing_episodes: 100
  testing_frequency: 100
  beta: 1e-3


critic:
  gamma: 0.99
  q_max: 10
  r_min: -10
  ucb_re: 0.0004
  ucb_rm: 0.0004
  ucb_p: 0.0004