id: Gym-Grid/Gridworld-Quicksand-Distract-4x4-v0
monitor:
  button_cell_id: 15
  button_flip_act: 1
  forbidden_states:


experiment:
  training_steps: 25000
  testing_episodes: 100
  testing_frequency: 100
  beta1: 0.01
  beta2: 0.5

critic:
  gamma: 0.99
  joint_max_q: 10
  obsrv_max_q: 100
  env_min_r: -10
  mon_max_r: 0
  ucb_re: 0.004
  ucb_rm: 0.004
  ucb_p: 0.004
