id: Gym-Grid/Gridworld-Quicksand-Distract-4x4-v0
monitor:
  button_cell_id: 15
  button_flip_act: 1
  forbidden_states:


experiment:
  training_steps: 15000
  testing_episodes: 1000
  testing_frequency: 100
  beta2: 0.01

critic:
  gamma: 0.99
  joint_max_q: 10
  env_min_r: -10
  ucb_re: 0.0004
  ucb_rm: 0.0004
  ucb_p: 0.0004
