id: Gym-Grid/Gridworld-Quicksand-Distract-4x4-v0
monitor:
  button_cell_id: 0
  button_flip_act: 0
  forbidden_states:


experiment:
  training_steps: 20000
  testing_episodes: 100
  testing_frequency: 100
  beta: 1.025

critic:
  gamma: 0.99
  joint_max_q: 1
  env_min_r: -10
  ucb_a: 0.0004
  ucb_b: 0.0004
  ucb_c: 0.0004
