id: Gym-Grid/Gridworld-Corridor-3x4-v0
monitor:
  button_cell_id: 8
  button_flip_act: 1
  forbidden_states:


experiment:
  training_steps: 20000
  testing_episodes: 100
  testing_frequency: 100
  beta: 1e-1

critic:
  gamma: 0.99
  q_max: 10
  r_min: -0.1
  ucb_re: 0.004
  ucb_rm: 0.004
  ucb_p: 0.004