id: Gym-Grid/Gridworld-Empty-Distract-6x6-v0
monitor:
  button_cell_id: 31
  button_flip_act: 1
  forbidden_states:
    - 2
    - 8
    - 14
    - 20
    - 26
    - 10
    - 16
    - 22
    - 28
    - 34

experiment:
  training_steps: 35000
  testing_episodes: 100
  testing_frequency: 100

critic:
  gamma: 1
  q_max: 18
  q_min: -100
  beta: 1
  ucb_re: 0.0004
  ucb_rm: 0.0004
  ucb_p: 0.0004