id: Gym-Grid/Gridworld-Corridor-3x4-v0
monitor:
  button_cell_id: 8
  button_flip_act: 1
  forbidden_states:


experiment:
  training_steps: 15000
  testing_episodes: 100
  testing_frequency: 100
  beta: 1.005

critic:
  gamma: 0.99
  joint_max_q: 10
  env_min_r: -0.1
  ucb_a: 0.004
  ucb_b: 0.004
