id: Gym-Grid/RiverSwim-6-v0
monitor:
  button_cell_id: 0
  button_flip_act: 0
  forbidden_states:


experiment:
  training_steps: 20000
  testing_episodes: 100
  testing_frequency: 100
  beta1: 0.01
  beta2: 0.5

critic:
  gamma: 0.99
  joint_max_q: 300
  env_min_r: 0
  ucb_re: 0.5
  ucb_rm: 0.5
  ucb_p: 0.5
