id: Gym-Grid/RiverSwim-6-v0
monitor:
  button_cell_id: 0
  button_flip_act: 0
  forbidden_states:


experiment:
  training_steps: 20000
  testing_episodes: 100
  testing_frequency: 100
  kappa_base: 1.005

critic:
  gamma: 0.99
  joint_max_q: 30
  env_min_r: 0
  beta_e: 0.005
  beta_m: 0.005
  beta: 0.01
  beta_obs: 0.01
  beta_kl_ucb: 0.05

