id: Gym-Grid/RiverSwim-6-v0
monitor:
  tmp:
    tmp: null

experiment:
  training_steps: 20000
  testing_episodes: 100
  testing_frequency: 100

critic:
  gamma: 0.99
  q_max: 484
  q_min: -42
  beta: 1e-2
  ucb_re: 0.04
  ucb_rm: 0.4
  ucb_p: 0.4