id: Gym-Grid/Gridworld-TwoRoom-Quicksand-3x5-v0
monitor:
  button_cell_id: 13
  button_flip_act: 1
  forbidden_states:
    - 7
    - 8


experiment:
  training_steps: 15000
  testing_episodes: 100
  testing_frequency: 100
  beta: 0.1


critic:
  gamma: 0.99
  joint_max_q: 10
  obsrv_max_q: 100
  env_min_r: -1
  mon_max_r: 0
  ucb_re: 0.004
  ucb_rm: 0.0004
  ucb_p: 0.0004
  ucb_obsrv_r: 2
  ucb_obsrv_p: 0.1