id: Gym-Grid/Gridworld-TwoRoom-Quicksand-3x5-v0
monitor:
  button_cell_id: 13
  button_flip_act: 1
  forbidden_states:
    - 7
    - 8


experiment:
  training_steps: 15000
  testing_episodes: 100
  testing_frequency: 100
  beta: 0.5


critic:
  gamma: 0.99
  q_max: 10
  r_min: -1
  ucb_re: 0.004
  ucb_rm: 0.0004
  ucb_p: 0.0004