id: Gym-Grid/Gridworld-TwoRoom-Quicksand-3x5-v0
monitor:
  button_cell_id: 13
  button_flip_act: 1
  forbidden_states:
    - 7
    - 8


experiment:
  training_steps: 25000
  testing_episodes: 100
  testing_frequency: 100
  beta2: 0.05

critic:
  gamma: 0.99
  joint_max_q: 10
  env_min_r: -10
  ucb_re: 0.004
  ucb_rm: 0.004
  ucb_p: 0.004
  vi_iter: 10