hydra:
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: -1
    backend: null
    prefer: processes
    require: null
    verbose: 0
    timeout: null
    pre_dispatch: 2*n_jobs
    batch_size: auto
    temp_folder: null
    max_nbytes: null
    mmap_mode: r
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params:
      environment: distract, grid_det, hazard, oneway, river_swim, two_room
      experiment.hide_progress_bar: true
      experiment.datadir: data
      experiment.rng_seed: range(0, 1)
      monitor: ask, button
      monitor.prob: 1.00, 0.75, 0.50, 0.25, 0.10, 0.01
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    root:
      level: ERROR
    disable_existing_loggers: true
  job_logging:
    version: 1
    root:
      level: ERROR
    disable_existing_loggers: true
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: null
  overrides:
    hydra:
    - hydra/launcher=joblib
    - hydra/sweeper=manual_sweeper
    - hydra.mode=MULTIRUN
    task: []
  job:
    name: main
    chdir: null
    override_dirname: ''
    id: ???
    num: ???
    config_name: default
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /Users/alirezakazemipour/github/ofu
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /Users/alirezakazemipour/github/ofu/configs
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      monitor: ask
      environment: river_swim
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: disabled
      hydra/hydra_logging: disabled
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: manual_sweeper
      hydra/launcher: joblib
      hydra/output: default
  verbose: false
environment:
  id: Gym-Grid/RiverSwim-6-v0
  monitor:
    button_cell_id: 0
    button_flip_act: 0
    forbidden_states: null
  experiment:
    training_steps: 20000
    testing_episodes: 100
    testing_frequency: 100
    beta1: 0.05
    beta2: 0.05
  critic:
    gamma: 0.99
    joint_max_q: 484
    env_min_r: -1
    ucb_re: 0.04
    ucb_rm: 0.4
    ucb_p: 0.4
  render_mode: null
monitor:
  id: Ask
  prob: 0.1
experiment:
  datadir: null
  rng_seed: 0
  hide_progress_bar: false
