# @package _global_
# @package hydra.sweeper
_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null
params:
  environment: grid
  experiment: short
  experiment.hide_progress_bar: True
  experiment.datadir: data
  experiment.rng_seed: range(0, 100)
  monitor: partial_obs_ask, partial_obs_button, never_partial_obs_ask, never_partial_obs_button
  monitor.prob: 1, 0.1
  agent.critic.q0: .97
  agent.critic.ucb_re: 5e-4
  agent.critic.ucb_rm: 5e-4
  agent.critic.ucb_p: 5e-4
  agent.critic.beta: 1e-2
