# @package _global_
# @package hydra.sweeper
_target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
max_batch_size: null
params:
  environment: river_swim
  experiment.hide_progress_bar: True
  experiment.datadir: data
  experiment.rng_seed: range(0, 5)
  monitor: ask, button
  monitor.prob: 1.00
